
import bank.manager.accInfo;
import bank.manager.depositMoney;
import bank.manager.withdrawMoney;
import control.login;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import user.user;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author respect
 */
public class mainFrame extends javax.swing.JFrame {

    private user user = new user();
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        lblLoginGirisYapiniz = new javax.swing.JLabel();
        lblLoginEmail = new javax.swing.JLabel();
        lblLoginPassword = new javax.swing.JLabel();
        txtLoginEmail = new javax.swing.JTextField();
        passLoginPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        lblMerhabaName = new javax.swing.JLabel();
        btnAccInfo = new javax.swing.JButton();
        btnDepositMoney = new javax.swing.JButton();
        btnWithdrawMoney = new javax.swing.JButton();
        btnTransactions = new javax.swing.JButton();
        lblMoney = new javax.swing.JLabel();
        accInfoPanel = new javax.swing.JPanel();
        lblInfoMoney = new javax.swing.JLabel();
        lblInfoPhoneNumber = new javax.swing.JLabel();
        btnInfoGeriDon = new javax.swing.JButton();
        lblInfoIsımSoyIsim = new javax.swing.JLabel();
        lblInfoWithdrawMinusMoney = new javax.swing.JLabel();
        depositMoneyPanel = new javax.swing.JPanel();
        btn100Yatir = new javax.swing.JButton();
        lblYatirmakIstediginMiktar = new javax.swing.JLabel();
        btn250Yatir = new javax.swing.JButton();
        btn300Yatir = new javax.swing.JButton();
        btn1500Yatir = new javax.swing.JButton();
        btn1000Yatir = new javax.swing.JButton();
        btn500Yatir = new javax.swing.JButton();
        lblMiktarGiriniz = new javax.swing.JLabel();
        txtParaMiktari = new javax.swing.JTextField();
        btnYatir = new javax.swing.JButton();
        lblDepositMoneyErrMsg = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        withdrawMoneyPanel = new javax.swing.JPanel();
        lblCekmekIstediginMiktar = new javax.swing.JLabel();
        btn100Cek = new javax.swing.JButton();
        btn250Cek = new javax.swing.JButton();
        btn300Cek = new javax.swing.JButton();
        btn1500Cek = new javax.swing.JButton();
        btn1000Cek = new javax.swing.JButton();
        btn500Cek = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();
        txtParaCekmeMiktari = new javax.swing.JTextField();
        lblCekmeMiktarGiriniz = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblWithdrawMoneyErrMsg = new javax.swing.JLabel();
        TransactionComplete = new javax.swing.JPanel();
        lblTransactionMsg = new javax.swing.JLabel();
        btnTransactionBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Parent.setLayout(new java.awt.CardLayout());

        lblLoginGirisYapiniz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLoginGirisYapiniz.setText("Giriş yapınız");

        lblLoginEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLoginEmail.setText("Email :");

        lblLoginPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLoginPassword.setText("Şifre :");

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setText("Giriş yap");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblLoginGirisYapiniz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(lblLoginEmail)
                                .addGap(20, 20, 20)
                                .addComponent(txtLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(lblLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(passLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblLoginGirisYapiniz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginPassword)
                    .addComponent(passLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Parent.add(loginPanel, "card2");

        lblMerhabaName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAccInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAccInfo.setText("Hesap bilgileri");
        btnAccInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccInfoActionPerformed(evt);
            }
        });

        btnDepositMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDepositMoney.setText("Para yatır");
        btnDepositMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositMoneyActionPerformed(evt);
            }
        });

        btnWithdrawMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnWithdrawMoney.setText("Para çek");
        btnWithdrawMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawMoneyActionPerformed(evt);
            }
        });

        btnTransactions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTransactions.setText("Son yapılan işlemler");

        lblMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTransactions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAccInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnDepositMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWithdrawMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblMerhabaName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMerhabaName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnAccInfo)
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositMoney)
                    .addComponent(btnTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnWithdrawMoney)
                .addGap(121, 121, 121))
        );

        Parent.add(menuPanel, "card3");

        lblInfoMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblInfoPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnInfoGeriDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInfoGeriDon.setText("Geri dön");
        btnInfoGeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoGeriDonActionPerformed(evt);
            }
        });

        lblInfoIsımSoyIsim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblInfoWithdrawMinusMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout accInfoPanelLayout = new javax.swing.GroupLayout(accInfoPanel);
        accInfoPanel.setLayout(accInfoPanelLayout);
        accInfoPanelLayout.setHorizontalGroup(
            accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInfoIsımSoyIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(accInfoPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accInfoPanelLayout.createSequentialGroup()
                        .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInfoPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInfoMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(lblInfoWithdrawMinusMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInfoGeriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        accInfoPanelLayout.setVerticalGroup(
            accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoIsımSoyIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoWithdrawMinusMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(lblInfoPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnInfoGeriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        Parent.add(accInfoPanel, "card4");

        btn100Yatir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn100Yatir.setText("100");
        btn100Yatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100YatirActionPerformed(evt);
            }
        });

        lblYatirmakIstediginMiktar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYatirmakIstediginMiktar.setText("Yatırmak istediğiniz miktarı seçiniz");

        btn250Yatir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn250Yatir.setText("250");
        btn250Yatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn250YatirActionPerformed(evt);
            }
        });

        btn300Yatir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn300Yatir.setText("300");
        btn300Yatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn300YatirActionPerformed(evt);
            }
        });

        btn1500Yatir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn1500Yatir.setText("1500");
        btn1500Yatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1500YatirActionPerformed(evt);
            }
        });

        btn1000Yatir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn1000Yatir.setText("1000");
        btn1000Yatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000YatirActionPerformed(evt);
            }
        });

        btn500Yatir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn500Yatir.setText("500");
        btn500Yatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500YatirActionPerformed(evt);
            }
        });

        lblMiktarGiriniz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMiktarGiriniz.setText("Miktar giriniz :");

        txtParaMiktari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnYatir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnYatir.setText("Yatır");
        btnYatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYatirActionPerformed(evt);
            }
        });

        lblDepositMoneyErrMsg.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        btnBack1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnBack1.setText("Geri dön");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoGeriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositMoneyPanelLayout = new javax.swing.GroupLayout(depositMoneyPanel);
        depositMoneyPanel.setLayout(depositMoneyPanelLayout);
        depositMoneyPanelLayout.setHorizontalGroup(
            depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn300Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn100Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn250Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn500Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1000Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1500Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                .addGroup(depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblYatirmakIstediginMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblDepositMoneyErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnBack1))
                    .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblMiktarGiriniz, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParaMiktari, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnYatir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        depositMoneyPanelLayout.setVerticalGroup(
            depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblYatirmakIstediginMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDepositMoneyErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btn300Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depositMoneyPanelLayout.createSequentialGroup()
                        .addGroup(depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn500Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn100Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1000Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn250Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btn1500Yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(depositMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMiktarGiriniz, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParaMiktari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYatir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Parent.add(depositMoneyPanel, "card5");

        lblCekmekIstediginMiktar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblCekmekIstediginMiktar.setText("Çekmek istediğiniz miktarı seçiniz");

        btn100Cek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn100Cek.setText("100");
        btn100Cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100CekActionPerformed(evt);
            }
        });

        btn250Cek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn250Cek.setText("250");
        btn250Cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn250CekActionPerformed(evt);
            }
        });

        btn300Cek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn300Cek.setText("300");
        btn300Cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn300CekActionPerformed(evt);
            }
        });

        btn1500Cek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn1500Cek.setText("1500");
        btn1500Cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1500CekActionPerformed(evt);
            }
        });

        btn1000Cek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn1000Cek.setText("1000");
        btn1000Cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000CekActionPerformed(evt);
            }
        });

        btn500Cek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn500Cek.setText("500");
        btn500Cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500CekActionPerformed(evt);
            }
        });

        btnCek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCek.setText("Çek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        txtParaCekmeMiktari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblCekmeMiktarGiriniz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCekmeMiktarGiriniz.setText("Miktar giriniz :");

        btnBack.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnBack.setText("Geri dön");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoGeriDonActionPerformed(evt);
            }
        });

        lblWithdrawMoneyErrMsg.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        javax.swing.GroupLayout withdrawMoneyPanelLayout = new javax.swing.GroupLayout(withdrawMoneyPanel);
        withdrawMoneyPanel.setLayout(withdrawMoneyPanelLayout);
        withdrawMoneyPanelLayout.setHorizontalGroup(
            withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn300Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn100Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn250Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn500Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1000Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1500Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                        .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(lblCekmeMiktarGiriniz, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                                        .addComponent(txtParaCekmeMiktari, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnBack))))
                            .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lblCekmekIstediginMiktar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblWithdrawMoneyErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        withdrawMoneyPanelLayout.setVerticalGroup(
            withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                .addComponent(lblCekmekIstediginMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWithdrawMoneyErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btn300Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdrawMoneyPanelLayout.createSequentialGroup()
                        .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn500Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn100Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1000Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn250Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btn1500Cek, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(withdrawMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCekmeMiktarGiriniz, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParaCekmeMiktari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(21, 21, 21))
        );

        Parent.add(withdrawMoneyPanel, "card7");

        lblTransactionMsg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        btnTransactionBack.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnTransactionBack.setText("Geri dön");
        btnTransactionBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoGeriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransactionCompleteLayout = new javax.swing.GroupLayout(TransactionComplete);
        TransactionComplete.setLayout(TransactionCompleteLayout);
        TransactionCompleteLayout.setHorizontalGroup(
            TransactionCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionCompleteLayout.createSequentialGroup()
                .addGroup(TransactionCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransactionCompleteLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblTransactionMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TransactionCompleteLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnTransactionBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        TransactionCompleteLayout.setVerticalGroup(
            TransactionCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionCompleteLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(lblTransactionMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnTransactionBack, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        Parent.add(TransactionComplete, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(!txtLoginEmail.getText().isEmpty() && (passLoginPassword.getPassword().length != 0)) {
            try {
                user.setEmail(txtLoginEmail.getText());
                user.setPassword(String.valueOf(passLoginPassword.getPassword()));
                login login = new login();
                if(login.control(user)) {
                    Parent.removeAll();
                    Parent.add(menuPanel);
                    Parent.repaint();
                    Parent.revalidate();
                    getInfo(user);
                    lblMerhabaName.setText("Merhaba, " + user.getFirstName() + " " + user.getLastName());
                    lblMoney.setText("Bakiye : " + user.getMoney());
                } else {
                lblErrorMessage.setText("Giriş yapılırken sorun oluştu.");}
            } catch (SQLException ex) {
                lblErrorMessage.setText("Bağlantı hatası oluştu.");
            }
        } else {
            lblErrorMessage.setText("Tüm alanları doldurunuz.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnInfoGeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoGeriDonActionPerformed
        try {
            getInfo(user);
        } catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblMoney.setText("Bakiye : " + user.getMoney());
        lblErrorMessage.setText("");
        lblDepositMoneyErrMsg.setText("");
        lblWithdrawMoneyErrMsg.setText("");
        Parent.removeAll();
        Parent.add(menuPanel);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_btnInfoGeriDonActionPerformed

    private void btnAccInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccInfoActionPerformed
        try {
            getInfo(user);
            Parent.removeAll();
            Parent.add(accInfoPanel);
            Parent.repaint();
            Parent.revalidate();
            lblInfoIsımSoyIsim.setText("Merhaba, " + user.getFirstName() + " " + user.getLastName());
            lblInfoMoney.setText("Paranız : " + user.getMoney());
            lblInfoPhoneNumber.setText("Telefon numaranız : " + user.getPhoneNumber());
            lblInfoWithdrawMinusMoney.setText("Çekilebilinir eksi bakiye : -500");
        } catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAccInfoActionPerformed

    private void paraYatir(double yatirilacak) {
        double total = user.getMoney() + yatirilacak;
        int response = JOptionPane.showConfirmDialog(this, "Para yatırma işlemini onaylıyor musun?\nYatırılacak para : "+yatirilacak+" \nToplam olacak para : " + total, "Para yatırma", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        txtParaMiktari.setText("");
        if(response == JOptionPane.YES_OPTION) {
            try {
                depositMoney deposit = new depositMoney();
                deposit.money(user, yatirilacak);
                getInfo(user);
                lblTransactionMsg.setText(yatirilacak+"₺'a  yatırıldı.\nToplam paranız : " + user.getMoney());
                Parent.removeAll();
                Parent.add(TransactionComplete);
                Parent.repaint();
                Parent.revalidate();
            } catch (SQLException e) {
                lblDepositMoneyErrMsg.setText("Bağlantı oluşurken sorun oluştu.");
            }
        } else {
            lblDepositMoneyErrMsg.setText("İşlem iptal edildi.");
        }
    }
    
    private void btnDepositMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositMoneyActionPerformed
        Parent.removeAll();
        Parent.add(depositMoneyPanel);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_btnDepositMoneyActionPerformed

    
    private void btn250YatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn250YatirActionPerformed
        paraYatir(250);
    }//GEN-LAST:event_btn250YatirActionPerformed

    private void btn300YatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn300YatirActionPerformed
        paraYatir(300);
    }//GEN-LAST:event_btn300YatirActionPerformed

    private void btn500YatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500YatirActionPerformed
        paraYatir(500);
    }//GEN-LAST:event_btn500YatirActionPerformed

    private void btn1000YatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000YatirActionPerformed
        paraYatir(1000);
    }//GEN-LAST:event_btn1000YatirActionPerformed

    private void btn1500YatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1500YatirActionPerformed
        paraYatir(1500);
    }//GEN-LAST:event_btn1500YatirActionPerformed

    private void btn100YatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100YatirActionPerformed
        paraYatir(100);
    }//GEN-LAST:event_btn100YatirActionPerformed

    private void btnYatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYatirActionPerformed
        if(!txtParaMiktari.getText().isEmpty()) {
            double deger = Double.valueOf(txtParaMiktari.getText());
            if(deger < 10) {
                lblDepositMoneyErrMsg.setText("Miktar 10₺'nın altında olamaz.");
            } else {
                paraYatir(deger);
            }
        } else {
            lblDepositMoneyErrMsg.setText("Miktar boş olamaz.");
        }
    }//GEN-LAST:event_btnYatirActionPerformed

    private void paraCek(double cekilecek) {
        try {
            getInfo(user);
            double total = user.getMoney()- cekilecek;
            int response = JOptionPane.showConfirmDialog(this, "Para çekme işlemini onaylıyor musun?\nÇekilecek para : "+cekilecek+" \nİşlem sonucu paranız : " + total, "Para yatırma", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            txtParaCekmeMiktari.setText("");
            if(total < -500) {
                double cekilebilinir = user.getMoney()-(-500);
                lblTransactionMsg.setText("<html>Çekmek istediğiniz miktar ile hesap bakiyeniz -500'e ulaşmakta. <br>Güncel hesap bakiyeniz : " + user.getMoney() + "<br>Çekilebilinir hesap bakiyesi : " + cekilebilinir + "</html>");
                Parent.removeAll();
                Parent.add(TransactionComplete);
                Parent.repaint();
                Parent.revalidate();
            } else {
                if(response == JOptionPane.YES_OPTION) {
                    withdrawMoney withdraw = new withdrawMoney();
                    withdraw.money(user, cekilecek);
                    lblTransactionMsg.setText("<html>Hesabınızdan "+cekilecek+"₺ para çektiniz.<br>Güncel hesap bakiyeniz : "+total+" </html>");
                    Parent.removeAll();
                    Parent.add(TransactionComplete);
                    Parent.repaint();
                    Parent.revalidate();
                } else {
                    lblWithdrawMoneyErrMsg.setText("İşlem iptal edildi.");
                }
            }
        } catch (SQLException ex) {
            lblWithdrawMoneyErrMsg.setText("Bağlantı hatası oluştu.");
        }
    
    }
    
    private void btnWithdrawMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawMoneyActionPerformed
        Parent.removeAll();
        Parent.add(withdrawMoneyPanel);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_btnWithdrawMoneyActionPerformed

    private void btn100CekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100CekActionPerformed
        paraCek(100);
    }//GEN-LAST:event_btn100CekActionPerformed

    private void btn250CekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn250CekActionPerformed
        paraCek(250);
    }//GEN-LAST:event_btn250CekActionPerformed

    private void btn300CekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn300CekActionPerformed
        paraCek(300);
    }//GEN-LAST:event_btn300CekActionPerformed

    private void btn1500CekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1500CekActionPerformed
        paraCek(1500);
    }//GEN-LAST:event_btn1500CekActionPerformed

    private void btn1000CekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000CekActionPerformed
        paraCek(1000);
    }//GEN-LAST:event_btn1000CekActionPerformed

    private void btn500CekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500CekActionPerformed
        paraCek(500);
    }//GEN-LAST:event_btn500CekActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        if(!txtParaCekmeMiktari.getText().isEmpty()) {
            double deger = Double.valueOf(txtParaCekmeMiktari.getText());
            if(deger < 10) {
                lblWithdrawMoneyErrMsg.setText("Miktar 10₺'nın altında olamaz.");
            } else {
                paraCek(deger);
            }
        } else {
            lblWithdrawMoneyErrMsg.setText("Miktar boş olamaz.");
        }
    }//GEN-LAST:event_btnCekActionPerformed
    
    public void getInfo(user user) throws SQLException {
        accInfo getInfo = new accInfo();
        getInfo.info(user);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel TransactionComplete;
    private javax.swing.JPanel accInfoPanel;
    private javax.swing.JButton btn1000Cek;
    private javax.swing.JButton btn1000Yatir;
    private javax.swing.JButton btn100Cek;
    private javax.swing.JButton btn100Yatir;
    private javax.swing.JButton btn1500Cek;
    private javax.swing.JButton btn1500Yatir;
    private javax.swing.JButton btn250Cek;
    private javax.swing.JButton btn250Yatir;
    private javax.swing.JButton btn300Cek;
    private javax.swing.JButton btn300Yatir;
    private javax.swing.JButton btn500Cek;
    private javax.swing.JButton btn500Yatir;
    private javax.swing.JButton btnAccInfo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnDepositMoney;
    private javax.swing.JButton btnInfoGeriDon;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnTransactionBack;
    private javax.swing.JButton btnTransactions;
    private javax.swing.JButton btnWithdrawMoney;
    private javax.swing.JButton btnYatir;
    private javax.swing.JPanel depositMoneyPanel;
    private javax.swing.JLabel lblCekmeMiktarGiriniz;
    private javax.swing.JLabel lblCekmekIstediginMiktar;
    private javax.swing.JLabel lblDepositMoneyErrMsg;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblInfoIsımSoyIsim;
    private javax.swing.JLabel lblInfoMoney;
    private javax.swing.JLabel lblInfoPhoneNumber;
    private javax.swing.JLabel lblInfoWithdrawMinusMoney;
    private javax.swing.JLabel lblLoginEmail;
    private javax.swing.JLabel lblLoginGirisYapiniz;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblMerhabaName;
    private javax.swing.JLabel lblMiktarGiriniz;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblTransactionMsg;
    private javax.swing.JLabel lblWithdrawMoneyErrMsg;
    private javax.swing.JLabel lblYatirmakIstediginMiktar;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPasswordField passLoginPassword;
    private javax.swing.JTextField txtLoginEmail;
    private javax.swing.JTextField txtParaCekmeMiktari;
    private javax.swing.JTextField txtParaMiktari;
    private javax.swing.JPanel withdrawMoneyPanel;
    // End of variables declaration//GEN-END:variables
}
